export const Services = {
  changePassword: 'change-password',
  clientRegister: 'client-register',
  clientApprove: 'client-approve',
  clientReject: 'client-reject',
  userCreate: 'user-create',
  userEdit: 'user-edit',
  nasabahCreate: 'nasabah-create',
  nasabahEdit: 'nasabah-edit',
  profileEdit: 'profile-edit',
  packageCreate: 'package-create',
  packageEdit: 'package-edit',
  productCreate: 'product-create',
  productEdit: 'product-edit',
  ppobAllMarginEdit: 'ppob-all-margin-edit',
  ppobEdit: 'ppob-edit',
}

export const Titles = {
  'change-password': 'Password changed',
  'client-register': 'New client registered',
  'client-approve': 'Request approved',
  'client-reject': 'Request rejected',
  'user-create': 'New user created',
  'user-edit': 'User updated',
  'nasabah-create': 'New nasabah created',
  'nasabah-edit': 'Nasabah updated',
  'profile-edit': 'Profile updated',
  'package-create': 'New package created',
  'package-edit': 'Package updated',
  'product-create': 'New product created',
  'product-edit': 'Product updated',
  'ppob-all-margin-edit': 'All services margin updated',
  'ppob-edit': 'PPOB updated',
}

export const Contents = {
  'change-password': "User's password changed",
  'client-register': 'New client registration request created',
  'client-approve': 'Client registration request approved',
  'client-reject': 'Client registration request rejected',
  'user-create': 'New user created: ',
  'user-edit': 'User`s info edited: ',
  'nasabah-create': 'New nasabah created: ',
  'nasabah-edit': 'Nasabah`s info updated: ',
  'profile-edit': 'Profile`s info updated',
  'package-create': 'New package created: ',
  'package-edit': 'Package`s info updated: ',
  'product-create': 'New product created: ',
  'product-edit': 'Product`s info updated: ',
  'ppob-all-margin-edit': 'All services margin updated',
  'ppob-edit': 'PPOB`s info updated: ',
}
